services:
  - type: web
    name: uhnw
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: HOSTNAME=0.0.0.0 PORT=${PORT:-3000} npm run start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
